# Generated by Django 4.2 on 2025-05-06 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn_book_image_book_year_userslibroteka_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='El ISBN debe tener 10 o 13 dígitos numéricos.', regex='^\\d{10}(\\d{3})?$')]),
        ),
    ]
